// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtmxzikrcgomtnthidqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0bXh6aWtyY2dvbXRudGhpZHFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NjUzNjgsImV4cCI6MjA2OTQ0MTM2OH0.R_ZYbD9COhfkPOOoyxiyBUz6sW2mxKXWpM6haFjheZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});